package com.princekumar.itams.ticket;

import com.princekumar.itams.asset.Asset;
import com.princekumar.itams.common.entity.BaseEntity;
import com.princekumar.itams.person.Person;
import jakarta.persistence.*;

import java.time.OffsetDateTime;
import java.util.EnumSet;
import java.util.Map;
import java.util.Set;

/**
 * A support ticket. State machine enforced in {@link #transitionTo(TicketStatus)}.
 * Ticket number is generated by the service after the first save (see
 * {@code TicketService#create}) using the format {@code TCK-YYYY-000123}.
 */
@Entity
@Table(name = "ticket")
public class Ticket extends BaseEntity {

    @Column(name = "ticket_number", nullable = false, length = 30, unique = true)
    private String ticketNumber;

    @Column(nullable = false, length = 200)
    private String subject;

    @Column(columnDefinition = "text", nullable = false)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TicketPriority priority;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private TicketStatus status = TicketStatus.OPEN;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "reporter_person_id", nullable = false, updatable = false)
    private Person reporter;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "related_asset_id")
    private Asset relatedAsset;

    @Column(name = "assigned_to_user_id")
    private Long assignedToUserId;

    @Column(name = "resolved_at")
    private OffsetDateTime resolvedAt;

    @Column(name = "closed_at")
    private OffsetDateTime closedAt;

    protected Ticket() { /* JPA */ }

    public Ticket(String subject, String description, TicketPriority priority,
                  Person reporter, Asset relatedAsset) {
        this.subject = subject;
        this.description = description;
        this.priority = priority;
        this.reporter = reporter;
        this.relatedAsset = relatedAsset;
    }

    // ── state machine ────────────────────────────────────────────────────────

    private static final Map<TicketStatus, Set<TicketStatus>> ALLOWED = Map.of(
        TicketStatus.OPEN,        EnumSet.of(TicketStatus.IN_PROGRESS, TicketStatus.CLOSED),
        TicketStatus.IN_PROGRESS, EnumSet.of(TicketStatus.WAITING, TicketStatus.RESOLVED, TicketStatus.CLOSED),
        TicketStatus.WAITING,     EnumSet.of(TicketStatus.IN_PROGRESS, TicketStatus.RESOLVED, TicketStatus.CLOSED),
        TicketStatus.RESOLVED,    EnumSet.of(TicketStatus.CLOSED, TicketStatus.IN_PROGRESS),
        TicketStatus.CLOSED,      EnumSet.noneOf(TicketStatus.class)
    );

    public void transitionTo(TicketStatus next) {
        if (!ALLOWED.get(this.status).contains(next)) {
            throw new IllegalStateException("Illegal ticket transition: " + this.status + " → " + next);
        }
        this.status = next;
        OffsetDateTime now = OffsetDateTime.now();
        if (next == TicketStatus.RESOLVED) this.resolvedAt = now;
        if (next == TicketStatus.CLOSED)   this.closedAt = now;
    }

    // ── setters ──────────────────────────────────────────────────────────────

    public void setTicketNumber(String tn) { this.ticketNumber = tn; }
    public void setPriority(TicketPriority p) { this.priority = p; }
    public void setAssignedToUserId(Long userId) { this.assignedToUserId = userId; }

    // ── getters ──────────────────────────────────────────────────────────────

    public String getTicketNumber() { return ticketNumber; }
    public String getSubject() { return subject; }
    public String getDescription() { return description; }
    public TicketPriority getPriority() { return priority; }
    public TicketStatus getStatus() { return status; }
    public Person getReporter() { return reporter; }
    public Asset getRelatedAsset() { return relatedAsset; }
    public Long getAssignedToUserId() { return assignedToUserId; }
    public OffsetDateTime getResolvedAt() { return resolvedAt; }
    public OffsetDateTime getClosedAt() { return closedAt; }
}
